# Generated by Django 2.1.7 on 2019-04-02 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.CharField(max_length=250)),
                ('incident', models.CharField(max_length=250)),
                ('date_solved', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
