# Generated by Django 2.2.5 on 2020-02-25 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dirs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(max_length=4)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
                ('otchestvo', models.CharField(default='', max_length=256)),
                ('director', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Директора',
                'verbose_name_plural': 'Директора',
                'ordering': ('sap',),
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=16)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.TextField()),
                ('incident', models.CharField(max_length=30)),
                ('date_solved', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_status', models.CharField(default='', max_length=255)),
                ('criticality', models.CharField(choices=[('danger', 'danger'), ('warning', 'warning'), ('success', 'success')], max_length=7)),
            ],
            options={
                'verbose_name': 'Инциденты',
                'verbose_name_plural': 'Инциденты',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=16, unique=True)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-store',),
            },
        ),
    ]
