# Generated by Django 2.1.7 on 2019-04-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('-store',),
            },
        ),
    ]
