# Generated by Django 2.1.7 on 2019-04-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='problem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='store',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='store',
            field=models.CharField(max_length=16),
        ),
    ]
