# Generated by Django 2.1.7 on 2019-04-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190402_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='store',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
