# Generated by Django 2.1.7 on 2019-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190402_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('danger', 'danger'), ('warning', 'warning'), ('success', 'success')], max_length=7),
        ),
    ]
