# Generated by Django 2.1.7 on 2019-04-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190402_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('danger', 'danger'), ('warning', 'warning'), ('success', 'success')], max_length=7),
        ),
    ]
