# Generated by Django 2.1.7 on 2019-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190402_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='current_status',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
