# Generated by Django 2.2.5 on 2019-10-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190402_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('-created',), 'verbose_name': 'Инциденты', 'verbose_name_plural': 'Инциденты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-store',), 'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
