# Generated by Django 2.2.5 on 2019-11-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191011_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(max_length=4)),
                ('director', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Директора',
                'verbose_name_plural': 'Директора',
                'ordering': ('-sap',),
            },
        ),
    ]
